// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/chaoswall/route (interfaces: Repository)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	route "github.com/xescugc/chaoswall/route"
	reflect "reflect"
)

// RouteRepository is a mock of Repository interface
type RouteRepository struct {
	ctrl     *gomock.Controller
	recorder *RouteRepositoryMockRecorder
}

// RouteRepositoryMockRecorder is the mock recorder for RouteRepository
type RouteRepositoryMockRecorder struct {
	mock *RouteRepository
}

// NewRouteRepository creates a new mock instance
func NewRouteRepository(ctrl *gomock.Controller) *RouteRepository {
	mock := &RouteRepository{ctrl: ctrl}
	mock.recorder = &RouteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *RouteRepository) EXPECT() *RouteRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *RouteRepository) Create(arg0 context.Context, arg1, arg2 string, arg3 route.Route) (uint32, error) {
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *RouteRepositoryMockRecorder) Create(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*RouteRepository)(nil).Create), arg0, arg1, arg2, arg3)
}

// DeleteByCanonical mocks base method
func (m *RouteRepository) DeleteByCanonical(arg0 context.Context, arg1, arg2, arg3 string) error {
	ret := m.ctrl.Call(m, "DeleteByCanonical", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCanonical indicates an expected call of DeleteByCanonical
func (mr *RouteRepositoryMockRecorder) DeleteByCanonical(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCanonical", reflect.TypeOf((*RouteRepository)(nil).DeleteByCanonical), arg0, arg1, arg2, arg3)
}

// Filter mocks base method
func (m *RouteRepository) Filter(arg0 context.Context, arg1, arg2 string) ([]*route.Route, error) {
	ret := m.ctrl.Call(m, "Filter", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*route.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter
func (mr *RouteRepositoryMockRecorder) Filter(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*RouteRepository)(nil).Filter), arg0, arg1, arg2)
}

// FindByCanonical mocks base method
func (m *RouteRepository) FindByCanonical(arg0 context.Context, arg1, arg2, arg3 string) (*route.Route, error) {
	ret := m.ctrl.Call(m, "FindByCanonical", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*route.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCanonical indicates an expected call of FindByCanonical
func (mr *RouteRepositoryMockRecorder) FindByCanonical(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCanonical", reflect.TypeOf((*RouteRepository)(nil).FindByCanonical), arg0, arg1, arg2, arg3)
}

// UpdateByCanonical mocks base method
func (m *RouteRepository) UpdateByCanonical(arg0 context.Context, arg1, arg2, arg3 string, arg4 route.Route) error {
	ret := m.ctrl.Call(m, "UpdateByCanonical", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByCanonical indicates an expected call of UpdateByCanonical
func (mr *RouteRepositoryMockRecorder) UpdateByCanonical(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByCanonical", reflect.TypeOf((*RouteRepository)(nil).UpdateByCanonical), arg0, arg1, arg2, arg3, arg4)
}
