// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/chaoswall/user (interfaces: Repository)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	user "github.com/xescugc/chaoswall/user"
	reflect "reflect"
)

// UserRepository is a mock of Repository interface
type UserRepository struct {
	ctrl     *gomock.Controller
	recorder *UserRepositoryMockRecorder
}

// UserRepositoryMockRecorder is the mock recorder for UserRepository
type UserRepositoryMockRecorder struct {
	mock *UserRepository
}

// NewUserRepository creates a new mock instance
func NewUserRepository(ctrl *gomock.Controller) *UserRepository {
	mock := &UserRepository{ctrl: ctrl}
	mock.recorder = &UserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *UserRepository) EXPECT() *UserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *UserRepository) Create(arg0 context.Context, arg1 user.User) (uint32, error) {
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *UserRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*UserRepository)(nil).Create), arg0, arg1)
}

// DeleteByCanonical mocks base method
func (m *UserRepository) DeleteByCanonical(arg0 context.Context, arg1 string) error {
	ret := m.ctrl.Call(m, "DeleteByCanonical", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCanonical indicates an expected call of DeleteByCanonical
func (mr *UserRepositoryMockRecorder) DeleteByCanonical(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCanonical", reflect.TypeOf((*UserRepository)(nil).DeleteByCanonical), arg0, arg1)
}

// FindByCanonical mocks base method
func (m *UserRepository) FindByCanonical(arg0 context.Context, arg1 string) (*user.User, error) {
	ret := m.ctrl.Call(m, "FindByCanonical", arg0, arg1)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCanonical indicates an expected call of FindByCanonical
func (mr *UserRepositoryMockRecorder) FindByCanonical(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCanonical", reflect.TypeOf((*UserRepository)(nil).FindByCanonical), arg0, arg1)
}

// UpdateByCanonical mocks base method
func (m *UserRepository) UpdateByCanonical(arg0 context.Context, arg1 string, arg2 user.User) error {
	ret := m.ctrl.Call(m, "UpdateByCanonical", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByCanonical indicates an expected call of UpdateByCanonical
func (mr *UserRepositoryMockRecorder) UpdateByCanonical(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByCanonical", reflect.TypeOf((*UserRepository)(nil).UpdateByCanonical), arg0, arg1, arg2)
}
