version: "3"
services:
  chaoswall:
    build:
      context: ..
      dockerfile: docker/Dockerfile.chaoswall.dev
    ports:
      - '4000:4000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_NAME=chaoswall_develop
      - PORT=4000

  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - ./data/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
